version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform"
    directories:
      - "/"
    groups:
      terraform-modules:
        patterns:
          - "*terraform-modules*"
    schedule:
      interval: "daily"
